language: python

sudo: required

cache:
  bundler: true
  directories:
    - $HOME/docker

services:
    - docker

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

install:
  - docker pull lobradov/docker-espurna-builder

before_script:
  - env | grep -e BUILDER_ -e TRAVIS_  > env-file

before_cache:
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

env:
  global:
    - BUILDER_TOTAL_THREADS=3
  matrix:
    - BUILDER_THREAD=0
    - BUILDER_THREAD=1
    - BUILDER_THREAD=2

script:
- docker run -it --rm --env-file env-file -v ${TRAVIS_BUILD_DIR}:/usr/src/espurna lobradov/docker-espurna-builder -p
